#!/bin/bash

[[ -z "$1" || "$1" =~ --help|-h ]] && {
    echo "git show-last [--help|-h] <amount_of_commits>"
    echo "  alias of git show ...HEAD~<n>"
    exit 1
}
# isInteger
test "$1" -eq "$1" 2>/dev/null || {
    echo "Not an integer"
    exit 2
}

git show "...HEAD~$1"

