#!/bin/bash

[[ -z "$1" || "$1" =~ --help|-h ]] && {
    echo "git sa [--help|-h] <stash_index>"
    echo "  git stash apply but with --patch"
    exit 1
}
# isInteger
test "$1" -eq "$1" 2>/dev/null || {
    echo "Not an integer"
    exit 2
}

git checkout \
    --unified=2 --inter-hunk-context=2 \
    --patch "stash@{$1}"

